// Differential test of careditor/ctachm.js against real Java probe (CtachmProbe.java).
// Expected values were generated by running tools.CtachmProbe against Game.jar.
import test from 'node:test';
import assert from 'node:assert/strict';
import { Medium } from '../Medium.js';
import { Trackers } from '../Trackers.js';
import { ctachm } from './ctachm.js';
import { intArray, floatArray } from '../java.js';

function createMockEditor(text = '') {
  return {
    _text: text,
    _selStart: 0,
    _selEnd: text.length,
    getText() {
      return this._text;
    },
    setText(s) {
      this._text = s == null ? '' : s;
      this._selStart = 0;
      this._selEnd = this._text.length;
    },
    getSelectedText() {
      if (this._selStart < 0 || this._selEnd < this._selStart || this._selEnd > this._text.length) return '';
      return this._text.substring(this._selStart, this._selEnd);
    },
    replaceText(str, start, end) {
      if (start < 0) start = 0;
      if (end > this._text.length) end = this._text.length;
      if (start <= end) {
        this._text = this._text.substring(0, start) + str + this._text.substring(end);
      }
    },
    insertText(str, pos) {
      if (pos < 0) pos = 0;
      if (pos > this._text.length) pos = this._text.length;
      this._text = this._text.substring(0, pos) + str + this._text.substring(pos);
    },
    select(start, end) {
      this._selStart = Math.max(0, Math.min(start, this._text.length));
      this._selEnd = Math.max(this._selStart, Math.min(end, this._text.length));
    },
    getSelectionStart() {
      return this._selStart;
    },
    getSelectionEnd() {
      return this._selEnd;
    },
    requestFocus() {},
    hide() {},
  };
}

function createMockTextField(text = '') {
  return {
    _text: text,
    getText() {
      return this._text;
    },
    setText(s) {
      this._text = s == null ? '' : s;
    },
    requestFocus() {},
    hide() {},
  };
}

function createMockSmenu(val = 0) {
  return {
    select: val,
    no: 40,
    getSelectedIndex() {
      return this.select;
    },
    getItemCount() {
      return this.no;
    },
    add() {},
    hide() {},
  };
}

function setupCM() {
  const wv = [];
  for (let i = 0; i < 16; ++i) wv.push(createMockTextField());

  return {
    btn: 4,
    bx: intArray([100, 200, 300, 400]),
    by: intArray([50, 50, 50, 50]),
    bw: intArray([40, 40, 40, 40]),
    pessd: new Array(4).fill(false),
    xm: 0,
    ym: 0,
    mouses: 0,
    tab: 0,
    sfase: 0,
    dtab: 0,
    editor: createMockEditor(),
    srch: createMockTextField(),
    rplc: createMockTextField(),
    tnick: createMockTextField(),
    tpass: createMockTextField(),
    wv,
    slcar: createMockSmenu(),
    fontsel: createMockSmenu(),
    ctheme: createMockSmenu(),
    compcar: createMockSmenu(),
    cls: createMockSmenu(),
    simcar: createMockSmenu(),
    engine: createMockSmenu(),
    witho: createMockSmenu(),
    pubitem: createMockSmenu(707),
    pubtyp: createMockSmenu(),
    carname: 'testcar',
    scale: intArray([100, 100, 100]),
    oscale: intArray([100, 100, 100]),
    stat: intArray([150, 150, 150, 150, 150]),
    rstat: intArray([150, 150, 150, 150, 150]),
    carstat: [intArray([150, 150, 150, 150, 150])],
    phys: intArray([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]),
    rphys: intArray([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]),
    crash: intArray([50, 50, 50]),
    rcrash: intArray([50, 50, 50]),
    handling: 100,
    o: { colok: 0, fcol: intArray(3), scol: intArray(3), npl: 0, p: [], errd: false },
    // Real collaborators, not no-ops: ctachm calls setupo() unconditionally in
    // the Java, so stubbing it out would leave the call untested.
    m: new Medium(),
    t: new Trackers(),
    showMessageDialog() {},
    showConfirmDialog() { return 0; },
  };
}

test('button hit test and mouses release match Java probe', () => {
  const cm = setupCM();
  cm.xm = 102;
  cm.ym = 52;
  cm.mouses = 1;
  ctachm(cm);
  assert.equal(cm.pessd[0], true);
  assert.equal(cm.pessd[1], false);

  cm.xm = 201;
  cm.ym = 49;
  cm.mouses = -1;
  ctachm(cm);
  assert.equal(cm.mouses, 0);
});

test('tab 1 prefs toggle matches Java probe', () => {
  const cm = setupCM();
  cm.tab = 1;
  cm.prefs = false;
  cm.xm = 100;
  cm.ym = 50;
  cm.mouses = -1;
  ctachm(cm);
  assert.equal(cm.prefs, true);
});

test('tab 1 polygon mirror X-axis matches Java probe', () => {
  const cm = setupCM();
  cm.tab = 1;
  cm.mirror = true;
  cm.cntpls = 2;
  cm.editor.setText('p(100,-20,300)\nfs(150)\n');
  cm.editor.select(0, cm.editor.getText().length);
  cm.bx = intArray([100, 200, 300, 400, 500, 600]);
  cm.by = intArray([50, 50, 50, 50, 50, 50]);
  cm.bw = intArray([40, 40, 40, 40, 40, 40]);
  cm.btn = 6;
  cm.pessd = new Array(6).fill(false);
  cm.xm = 400;
  cm.ym = 50;
  cm.mouses = -1; // n = 3
  ctachm(cm);

  const expected = 'p(100,-20,300)\nfs(150)\n\n\n// Mirror of the 2 polygons above along the X axis:\n\np(-100,-20,300)\nfs(-150)\n\n\n// End of mirror';
  assert.equal(cm.editor.getText(), expected);
});

test('tab 2 subtab 2 scale adjustments match Java probe', () => {
  const cm = setupCM();
  cm.tab = 2;
  cm.dtab = 2;
  cm.scale = intArray([100, 100, 100]);
  cm.editor.setText('ScaleX(100)\nScaleY(100)\nScaleZ(100)\n<p>');
  cm.xm = 200;
  cm.ym = 50;
  cm.mouses = -1; // n = 1 -> ScaleX += 5
  ctachm(cm);

  assert.equal(cm.scale[0], 105);
  assert.equal(cm.scale[1], 100);
  assert.equal(cm.scale[2], 100);
  assert.equal(cm.editor.getText(), 'ScaleX(100)\nScaleX(105)\nScaleY(100)\nScaleZ(100)\n<p>');
});

test('tab 2 subtab 2 point shift X+10 matches Java probe', () => {
  const cm = setupCM();
  cm.tab = 2;
  cm.dtab = 2;
  cm.editor.setText('p(15,-25,35)\n');
  cm.btn = 20;
  cm.bx = intArray(20);
  cm.by = intArray(20);
  cm.bw = intArray(20);
  for (let i = 0; i < 20; ++i) {
    cm.bx[i] = (i + 1) * 50;
    cm.by[i] = 50;
    cm.bw[i] = 40;
  }
  cm.pessd = new Array(20).fill(false);
  cm.xm = 600;
  cm.ym = 50;
  cm.mouses = -1; // n = 11 -> X += 10
  ctachm(cm);

  assert.equal(cm.editor.getText(), 'p(25,-25,35)\n\n');
});

test('tab 2 subtab 4 stat balancing matches Java probe', () => {
  const cm = setupCM();
  cm.tab = 2;
  cm.dtab = 4;
  cm.statdef = true;
  cm.stat = intArray([150, 150, 150, 150, 150]);
  cm.bx = intArray([50, 100, 150, 200, 250]);
  cm.by = intArray([50, 50, 50, 50, 50]);
  cm.bw = intArray([40, 40, 40, 40, 40]);
  cm.xm = 50;
  cm.ym = 50;
  cm.mouses = -1; // n = 0 -> decrease stat[0]
  ctachm(cm);

  assert.deepEqual(Array.from(cm.stat), [146, 151, 151, 151, 151]);
});

test('tab 2 subtab 5 physics adjustment matches Java probe', () => {
  const cm = setupCM();
  cm.tab = 2;
  cm.dtab = 5;
  cm.pfase = 0;
  cm.phys = intArray([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]);
  cm.bx = intArray([50, 100, 150, 200, 250]);
  cm.by = intArray([50, 50, 50, 50, 50]);
  cm.bw = intArray([40, 40, 40, 40, 40]);
  cm.xm = 100;
  cm.ym = 50;
  cm.mouses = -1; // n = 1 -> phys[0] += 2
  ctachm(cm);

  assert.equal(cm.phys[0], 52);
});

test('tab 2 subtab 6 handling rating matches Java probe', () => {
  const cm = setupCM();
  cm.tab = 2;
  cm.dtab = 6;
  cm.rateh = true;
  cm.handling = 100;
  cm.bx = intArray([50, 100, 150, 200, 250]);
  cm.by = intArray([50, 50, 50, 50, 50]);
  cm.bw = intArray([40, 40, 40, 40, 40]);
  cm.xm = 50;
  cm.ym = 50;
  cm.mouses = -1; // n = 0 -> handling -= 2
  ctachm(cm);
  assert.equal(cm.handling, 98);

  cm.xm = 100;
  cm.ym = 50;
  cm.mouses = -1; // n = 1 -> handling += 2
  ctachm(cm);
  assert.equal(cm.handling, 100);
});

test('tab 2 polygon color RGBtoHSB matches Java probe', () => {
  const cm = setupCM();
  cm.o = {
    colok: 2,
    fcol: intArray(3),
    scol: intArray(3),
    npl: 1,
    p: [
      {
        c: intArray([200, 100, 50]),
        hsb: floatArray(3),
        gr: -13,
      },
    ],
  };
  cm.tab = 2;
  cm.dtab = 1;
  cm.bx = intArray([50, 100, 150, 200, 250]);
  cm.by = intArray([50, 50, 50, 50, 50]);
  cm.bw = intArray([40, 40, 40, 40, 40]);
  cm.xm = 150;
  cm.ym = 50;
  cm.mouses = -1; // n = 2 -> n17 = 2
  ctachm(cm);

  assert.equal(cm.o.p[0].hsb[0].toFixed(5), (0.055555552).toFixed(5));
  assert.equal(cm.o.p[0].hsb[1].toFixed(5), (0.75).toFixed(5));
  assert.equal(cm.o.p[0].hsb[2].toFixed(5), (0.78431374).toFixed(5));
  assert.equal(cm.o.p[0].gr, 1);
});
