// Differential test of careditor/shape.js against real Java probe (ShapeProbe.java).
// Expected values were generated by running tools.ShapeProbe against Game.jar.
import test from 'node:test';
import assert from 'node:assert/strict';
import { py, xs, ys, rot, crash, setheme, regx, regz, roofsqsh } from './shape.js';
import { Medium } from '../Medium.js';

function createMedium() {
  const m = new Medium();
  m.cz = 50;
  m.focus_point = 200;
  m.cx = 400;
  m.cy = 300;
  m.cntrn = 20;
  m.rand[0] = 5;
  m.rand[1] = 5;
  m.rand[2] = 5;
  m.diup[0] = false;
  m.diup[1] = false;
  m.diup[2] = false;
  m.trn = 0;
  return m;
}

function setupContO() {
  return {
    npl: 1,
    keyx: Int32Array.from([100, 200]),
    keyz: Int32Array.from([300, 400]),
    xz: 30,
    zy: 15,
    xy: 10,
    roofat: 50,
    p: [
      {
        n: 2,
        wz: 0,
        ox: Int32Array.from([110, 120]),
        oy: Int32Array.from([55, 60]),
        oz: Int32Array.from([310, 320]),
        nocol: false,
        glass: 0,
        bfase: 22,
        hsb: Float32Array.from([0.1, 0.3, 0.8]),
        c: Int32Array.from([100, 150, 200]),
        gr: 0,
        chip: 0,
        ctmag: 0.0,
      },
    ],
  };
}

test('py matches Java probe output on int32 overflow inputs', () => {
  // Expected from ShapeProbe.java
  assert.equal(py(null, -50000, 50000, -60000, 60000), -1369803776);
  assert.equal(py(null, 123456, -654321, -987654, 456789), -1591852614);
});

test('xs and ys match Java probe output', () => {
  const cm = { m: createMedium() };
  // Expected from ShapeProbe.java
  assert.equal(xs(cm, -80000, 30), -321200);
  assert.equal(xs(cm, 90000, 500), 36240);
  assert.equal(ys(cm, -70000, 20), -280900);
  assert.equal(ys(cm, 85000, 600), 28534);
});

test('rot matches Java probe output', () => {
  const cm = { m: createMedium() };
  const arrX = Int32Array.from([-5000, 10000, -15000]);
  const arrY = Int32Array.from([8000, -12000, 20000]);
  rot(cm, arrX, arrY, 100, -200, 45, 3);
  // Expected from ShapeProbe.java
  assert.deepEqual(Array.from(arrX), [-9304, 15444, -24860]);
  assert.deepEqual(Array.from(arrY), [1992, -1543, 3406]);
});

test('crash matches Java probe crshturn transitions', () => {
  const dummySound = { play() {} };
  const cm = {
    lowcrashs: [dummySound, dummySound, dummySound],
    crashs: [dummySound, dummySound, dummySound],
    crshturn: 0,
    crashup: false,
  };
  crash(cm, 150.0);
  assert.equal(cm.crshturn, 1);
  crash(cm, 200.0);
  assert.equal(cm.crshturn, 2);
  crash(cm, -180.0);
  assert.equal(cm.crshturn, 0);

  cm.crashup = true;
  crash(cm, 50.0);
  assert.equal(cm.crshturn, 2);
});

test('setheme records color values on widget/theme object', () => {
  const editor = {
    fg: null,
    bg: null,
    setForeground(c) { this.fg = c; },
    setBackground(c) { this.bg = c; },
  };
  const cm = {
    editor,
    deff: [10, 20, 30],
    defb: [40, 50, 60],
    cthm: 0,
  };
  setheme(cm);
  assert.deepEqual(editor.fg, [10, 20, 30]);
  assert.deepEqual(editor.bg, [40, 50, 60]);

  cm.cthm = 5;
  setheme(cm);
  assert.deepEqual(editor.fg, [0, 172, 255]);
  assert.deepEqual(editor.bg, [210, 234, 255]);
});

test('regx matches Java probe deformation output', () => {
  const cm = {
    m: createMedium(),
    o: setupContO(),
    hitmag: 1000,
    actmag: 50,
    crash: Int32Array.from([500, 20, 10]),
  };
  regx(cm, 0, 500.0, true);
  // Expected from ShapeProbe.java
  assert.equal(cm.hitmag, 1500);
  assert.equal(cm.actmag, 53);
  assert.deepEqual(Array.from(cm.o.p[0].ox), [111, 121]);
  assert.deepEqual(Array.from(cm.o.p[0].oz), [309, 319]);
  assert.equal(cm.o.p[0].bfase, 23);
  assert.deepEqual(Array.from(cm.o.p[0].c), [204, 184, 153]);
});

test('regz matches Java probe deformation output', () => {
  const cm = {
    m: createMedium(),
    o: setupContO(),
    hitmag: 2000,
    actmag: 100,
    crash: Int32Array.from([600, 30, 15]),
  };
  regz(cm, 0, -600.0, true);
  // Expected from ShapeProbe.java
  assert.equal(cm.hitmag, 1400);
  assert.equal(cm.actmag, 105);
  assert.deepEqual(Array.from(cm.o.p[0].ox), [108, 118]);
  assert.deepEqual(Array.from(cm.o.p[0].oz), [307, 317]);
  assert.equal(cm.o.p[0].bfase, 24);
  assert.deepEqual(Array.from(cm.o.p[0].c), [204, 184, 153]);
});

test('roofsqsh matches Java probe squash output', () => {
  const origMathRandom = Math.random;
  Math.random = () => 0.5; // Math.random() > 0.9 is false, matching ShapeProbe branch
  try {
    const cm = {
      m: createMedium(),
      o: setupContO(),
      hitmag: 500,
      squash: 0,
      crash: Int32Array.from([400, 15, 30]),
    };
    roofsqsh(cm, 400.0);
    // Expected from ShapeProbe.java
    assert.equal(cm.hitmag, 514);
    assert.equal(cm.squash, 4);
    assert.deepEqual(Array.from(cm.o.p[0].oy), [63, 66]);
    assert.equal(cm.o.p[0].bfase, 28);
    assert.deepEqual(Array.from(cm.o.p[0].c), [204, 184, 153]);
  } finally {
    Math.random = origMathRandom;
  }
});
