// The CarMaker instance: 142 fields, in the order and with the values its
// constructor (java-src/CarMaker.java:209-352) assigns them.
//
// The transpiled chunks are functions taking this object as `cm` and reading
// `cm.<field>` wherever the Java said `this.<field>`, so this file IS the
// stitching contract between them — a field missing here is a chunk quietly
// operating on undefined, which in int arithmetic becomes NaN and in a
// comparison becomes false.
//
// Not a class: the Java has no behaviour in the constructor beyond these
// assignments, and keeping it a plain object keeps the chunk boundary honest.

import { intArray, floatArray, objArray } from '../java.js';
import { Medium } from '../Medium.js';
import { Trackers } from '../Trackers.js';
import { Smenu } from '../Smenu.js';
import { TextArea, TextField } from './widgets.js';

/** Java `new int[a][b]`, zero-filled. */
const int2v = (rows) => rows.map((r) => intArray(r));
/** Java `new String[a][b]`: b is allocated but every element is null. */
const str2 = (a, b) => Array.from({ length: a }, () => new Array(b).fill(null));
/** Java `new soundClip[a][b]`. */
const obj2 = (a, b) => Array.from({ length: a }, () => objArray(b));

export function newCarMaker() {
  return {
    // Declared but not assigned in the Java constructor: the applet's
    // graphics context, its double buffer, its thread, the font metrics, the
    // logo image, the right-click menu, the two theme colours and the car
    // model. Java leaves them null and the code assigns them in init()/run();
    // named here so a typo is a missing property rather than a new one.
    rd: null,
    offImage: null,
    thredo: null,
    ftm: null,
    logo: null,
    popupMenu: null,
    defb: null,
    deff: null,
    o: null,
    exwist: false,
    apx: 0,
    apy: 0,
    focuson: true,
    btgame: new Array(2).fill(null),
    onbtgame: false,
    tab: 0,
    tabed: -1,
    loadedfile: false,
    carname: "",
    scar: "",
    suser: "Horaks",
    sfont: "Monospaced",
    sthm: 0,
    sfase: 0,
    slcar: new Smenu(2000),
    tutok: false,
    flk: 0,
    changed: false,
    lastedo: "",
    prefs: false,
    mirror: false,
    editor: new TextArea(),
    srch: new TextField(''),
    rplc: new TextField(''),
    fontsel: new Smenu(40),
    cfont: "Monospaced",
    ctheme: new Smenu(40),
    cthm: 0,
    cntprf: 0,
    cntpls: 0,
    cntchk: 0,
    npolys: 0,
    tomany: false,
    ox: 335,
    oy: 40,
    oz: 800,
    oxz: -90,
    oxy: 0,
    ozy: 0,
    m: new Medium(),
    t: new Trackers(),
    compo: objArray(16),
    right: false,
    left: false,
    up: false,
    down: false,
    rotl: false,
    rotr: false,
    plus: false,
    minus: false,
    in: false,
    out: false,
    pflk: false,
    breakbond: false,
    polynum: -1,
    prflk: 0,
    bfo: 0,
    dtab: 0,
    dtabed: -1,
    mouseon: -1,
    fcol: "",
    ofcol: "",
    scol: "",
    oscol: "",
    fhsb: floatArray([ 0.5, 0.5, 0.5 ]),
    shsb: floatArray([ 0.5, 0.5, 0.5 ]),
    scale: intArray([ 100, 100, 100 ]),
    oscale: intArray([ 100, 100, 100 ]),
    compcar: new Smenu(40),
    compsel: 0,
    adna: intArray([ 276, 276, 276, 276, 276, 276 ]),
    changed2: false,
    wv: objArray(16),
    defnow: false,
    aply1: "",
    aply2: "",
    aplyd1: false,
    aplyd2: false,
    forwheels: false,
    cls: new Smenu(40),
    simcar: new Smenu(40),
    stat: intArray([ 100, 100, 100, 100, 100 ]),
    rstat: intArray([ 0, 0, 0, 0, 0 ]),
    carstat: int2v([ [ 110, 81, 131, 98, 100 ], [ 200, 200, 88, 16, 16 ], [ 108, 80, 93, 114, 125 ], [ 146, 119, 100, 83, 72 ], [ 109, 85, 141, 96, 93 ], [ 128, 98, 102, 109, 123 ], [ 115, 139, 96, 117, 133 ], [ 120, 81, 145, 126, 128 ], [ 140, 122, 101, 113, 124 ], [ 110, 144, 100, 154, 92 ], [ 133, 122, 144, 115, 126 ], [ 107, 96, 96, 192, 189 ], [ 192, 200, 106, 92, 90 ], [ 88, 104, 88, 200, 200 ], [ 148, 150, 197, 95, 90 ], [ 112, 128, 120, 192, 128 ] ]),
    carsel: 0,
    clsel: 0,
    statdef: false,
    pfase: 0,
    phys: intArray([ 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50 ]),
    rphys: intArray([ 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50 ]),
    crash: intArray([ 50, 50, 50 ]),
    rcrash: intArray([ 50, 50, 50 ]),
    pname: [ "Handbrake", "Turning Sensitivity", "Tire Grip", "Bouncing", "Empty", "Lifts Others", "Gets Lifted", "Pushes Others", "Gets Pushed", "Aerial Rotation Speed", "Aerial Control/Gliding" ],
    pnx: intArray([ 62, 20, 76, 71, 60, 38, 44, 20, 33, 320, 324 ]),
    usage: [ "Handbrake:\nThis defines the hand braking power of the car.\nThe more handbrake the car has the faster it brakes when you press Spacebar while driving.\nBut also the lesser the Handbrake the more the car can drift when you press Spacebar.\n\n", "Turning Sensitivity:\nThis defines how fast the car turns (or how fast the wheels respond to turning).\nThe more turning sensitive the faster the car turns and responds.\n\nWhen designing a fast car that is more racing oriented high turning sensitivity is     \nrecommended for the car to be able to take sharp and quick turns.\nHowever too much turning sensitivity can make the car hard to drive!\n\nWhen designing a slower and bigger car (like El King) lower turning sensitivity is\nrecommended for a more realistic effect.\n\n", "Tires Grip:\nThis defines the griping power of the car\u2019s wheels on the ground.\n\nThe more griping the more the cars sticks to track.\nThe less gripping the more the car drifts in the turns.\n\nSome drifting can be helpful as it makes the car drive smoother while less drifting can\nmake the car more irritable, it depends on how you like to drive the car and how it\nfeels for you.\n\n", "Bouncing:\nThis defines how the car bounces back when it hits the ground or obstacles.\n\nBouncing can help when performing stunts as when you land up side down\nif the car bounces it can be filliped over before landing again to avoid a 'bad landing'.\n\nHowever bouncing is not helpful in controlling the car and in racing.\n\n", "If you can read this then you are decompiling the code! Please don\u2019t bother trying to allow the car maker to give you max stats, the stats get check on the server before the car can be accepted. Just to save you sometime.", "Lifts Others:\nThis defines if the car lifts up other cars when it collides with them from the front and\nhow high it can lift them.\n\nDoes the car have a pointy nose like MAX Revenge, Radical One or La Vita Crab, a\npointy nose/front part that can go under the wheels of other cars and lift them?\nIf so then give it some Lifts Others.\n\nIf it has a nose/front part that is a block like most cars then give it 0 Lifts Others.\n\n", "Gets Lifted:\nThis defines if the car can get lifted over other cars when it collides with them and how\nhigh it can get lifted.\n\nIs the car higher off the ground like Wow Caninaro or has big wheels like Dr Monstaa,\nshould its jump over cars when it collides with them?\nIf so then give it some Gets Lifted depending on how high it should go.\n\nIf the car is lower to the ground like most cars then it should have 0 Gets Lifted\n\n", "Pushes Others:\nThis defines if the car pushes other cars away when it collides with them and how far it\ncan push them.\n\nIs the car a heavy car with a strong body like MASHEEN or El King, where when it\ncollides with other cars it pushes them away?\nOr does the car have special bumpers or body parts for pushing cars away like Sword of\nJustice has?\nIf so then give it some Pushes Others depending how strong you think it can push cars.\n\nIf it is a car like any other car, with an average weight and body strength then you should\ngive it 0 Pushes Others.\n\n", "Gets Pushed:\nThis defines if the car gets pushed away when it collides with other cars and how far it\ngets pushed away.\n\nIf the car is lighter then most cars, then it should get pushed away when it collides with\nothers cars.\nGetting pushed can be helpful if the car is week because it gets it away from the danger\n(from the car that hit it) faster, making it take lesser hits and escape better.\nHowever getting pushed is not helpful when racing.\n\n", "Aerial Rotation Speed:\nThis adjusts how fast the car can rotate and flip in the air when its performing a stunt.\n\nThis variable also depends on how much the \u2018Stunts\u2019 stat of the car is, if the car has a\nhigh Stunts stat then this variable will have a much bigger effect, if it has low Stunts stat\nthe variable will have a lower effect.\n\nIf you think the car is rotating too fast or too slow in the air when performing a stunt use\nthis variable to adjust that.\n\nIf the aerial rotation is too fast it can make the car hard to control in the air as it flips and\nhard to land upright.\n\nIf the car is a big and heavy car like MASHHEN or El King then it should have low\naerial rotation for a realistic effect.\n\n", "Aerial Control/Gliding:\nThis adjusts the cars ability to push itself in the air and glide when performing stunts!\n\nIf you don\u2019t know, in the game:\nBackward looping pushes the car upwards. \nForward looping pushes the car forwards. \nLeft and right rolling pushes the car left and right. \n\nThis variable adjust the power if this aerial push.\n\nThe variable also depends on how much the \u2018Stunts\u2019 stat of the car is, if the car has a\nhigh Stunts stat then this variable will have a much bigger effect, if it has low Stunts stat\nthe variable will have a lower effect.\n\nIf the car has some kind of wings or fins like Radical One or Kool Kat have then it should\nhave higher aerial control and gliding ability.\n\n", "Crash Look Test!\nThis defines how the car will look when it gets damaged.\nOr in other words what the car will look like as it gets damaged until it becomes wasted!\n\nIMPORTANT:\nYou need to perform a 'Normal Crash' test with a 'Roof Crash' test until the car gets totally destroyed (gets wasted and burns).\nYou need to also try a 'Normal Crash' test alone (without the roof crash) until the car gets wasted!\nA 'Roof Crash' happens significantly more when the car falls on its roof from a high jumps.\nA 'Normal Crash' is what happens as the car crashes normally with other cars and obstacles.\n\nClick any of adjustment variable names \u2018Radius\u2019, \u2018Magnitude\u2019 and \u2018Roof Destruction\u2019 to learn about their effect.\n\n>  You must perform the crash test more then once in order to make sure that this is how your want the car to look as it gets damaged\nuntil total destruction.", "Crash Radius:\nThe radius around the crash at which the polygons/pieces that lay inside it get\naffected.\n\nOr basically in other words the number of pieces that get affected on collision (the pieces\naround the crash location).\n\nIncreasing the radius will result in more pieces/polygons around the point of collision\ngetting crashed and distorted.\nDecreasing the radius means less pieces/polygons around the collision point getting\ndistorted and crashed.\n\n", "Crash Magnitude:\nThe magnitude of the distortion and indentation to occur on the effected pieces/polygons.\n\nOr basically in other words the amount of destruction that happens to each piece when\ncrashed.\n\nHigher magnitude means the piece gets more destructed from an amount of damage,\nlower magnitude means the piece gets less destructed from that same amount of damage.\n\n", "Roof Destruction:\nThe amount of destruction to occur on the car\u2019s top.\nThe length of indentation and destruction to happen from above.\n\nTo really see this variable's effect try crashing the roof alone (without a normal crash),\ntry more then once while fixing the car and changing the variable\u2019s value to see the\ndifference.\n\nThe roof crash normally happens in the game when the car lands upside down from a\njump or when a big car like Dr Monstaa steps on it.\n\n" ],
    hitmag: 0,
    actmag: 0,
    squash: 0,
    crashok: false,
    crashleft: false,
    crashs: objArray(3),
    lowcrashs: objArray(3),
    engine: new Smenu(40),
    engs: obj2(5, 5),
    engsel: 0,
    engon: false,
    witho: new Smenu(40),
    tested: false,
    rateh: false,
    handling: 140,
    logged: 0,
    tnick: new TextField(''),
    tpass: new TextField(''),
    pubitem: new Smenu(707),
    pubtyp: new Smenu(40),
    nmc: 0,
    roto: 0,
    mycars: new Array(20).fill(''),
    maker: new Array(20).fill(''),
    pubt: intArray(20),
    clas: intArray(20),
    addeda: str2(20, 5000),
    nad: intArray(20),
    justpubd: "",
    pessd: [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ],
    bx: intArray([ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]),
    by: intArray([ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]),
    bw: intArray([ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]),
    btn: 0,
    mouses: 0,
    xm: 0,
    ym: 0,
    sls: -1,
    sle: -1,
    crshturn: 0,
    crashup: false,
    openm: false,
    mousdr: false,
    waso: false,
    objfacend: false,
    multf10: false,
  };
}
